### ISSUE TITLE
The timer and the score box is not aligned.

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#28]

**Comment by rajneeshchhawari** [comment]
Issue solved you can see in next update

**Comment by administer** [comment]
Still not aligned

**Comment by rajneeshchhawari** [comment]
not its fine i have updated code

**Comment by administer** [comment]
Still not resolved. Actually, it has introduced another bug with: question details overlap the image.

**Comment by rajneeshchhawari** [comment]
done
